name: second github-action
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting && Print goodbye
        run: |
          echo "Hello World"
          echo "Bye"
